### ISSUE TITLE
No secrets found

### ISSUE THREAD

**Issue by ikauzak** [kir4h/rvault#3]
Hey there. Tried to use the `rvaul list secret -p appgo` , but it is not finding any secret in there.

So i tried to debug it a little bit and it seems that it is hitting the `secret/metadata/appgo` endpoint... and the correct one should be `appgo/metadata`, since my root kv name is `appgo`...
```
rvault list secret -k 2 -p appgo  -v=0 -v 5
I0901 07:43:38.892336  698249 kv.go:77] Using kv version '2' for engine 'secret'
I0901 07:43:38.892423  698249 list.go:35] Listing for secret/metadata/appgo/
I0901 07:43:39.165269  698249 list.go:48] No secrets found for path appgo
```

Got the right endpoint by using the `vault -output-curl-string`.
```
vault kv list -output-curl-string appgo
curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" https://${VAULT_ADDR}/v1/appgo/metadata?list=true
```

Think i am using the lastest version:
```
rvault --version
rvault version 0.2.1 
Commit: 5e6163d
Date: 2020-07-28T17:21:50Z
```

Thanks for the help.

**Comment by ikauzak** [comment]
Nevermind, just figured out that i should have used the right syntax:
```
rvault list appgo
```

**Comment by kir4h** [comment]
> Nevermind, just figured out that i should have used the right syntax:
> 
> ```
> rvault list appgo
> ```

Sorry for the late reply, I didn't get notified by Github (I'll check my settings, I assumed I would get a notification on new issues).

Yup, thing there is that the mandatory argument is the name of the engine (`secret` is the default one), so you should use `appgo` in your scenario as you finally did :)
