### ISSUE TITLE
Unsupported engine type `generic`

### ISSUE THREAD

**Issue by jtatum** [kir4h/rvault#7]
Yeah, we're running a vault so old that our kv secrets engine is called generic.

**Comment by kir4h** [comment]
I´m afraid only KV engine is supported (I think when I had a use case for this I only tested it on kv v1/v2). I am using `github.com/hashicorp/vault/api` to interact with Vault, so as long as `generic` is still supported there I guess it could be added. 

What Vault version are you using?
