### ISSUE TITLE
Unable to use wildcard/* when running rvault read commands

### ISSUE THREAD

**Issue by ramrajkonuganti** [kir4h/rvault#8]
I'm trying to read the secret from vault using rvault read commands following the instructions provided in the documentations. 

I'm able to read secrets for a specified path 
ex: rvault read secret -f json -k 2 -p "A/B/"

{"A/B/test":{"test":"value"},"A/B/test2":{"test2":"value"},"A/B/test3":{"test3":"value"}, "A/B/sample":{"sample":"value"}}

but I'm not able to run this command using a wildcard /* so that I don't have to enter the full path.
Ex:
rvault read secret -f json -k 2 -p "A/B/*"
ADDRESS IS https://<hostname>
I0228 20:21:17.652282 1756279 list.go:48] No secrets found for path A/B/*
{}

also I'm getting parse errors when I'm using this command as per the document.

rvault read secret -f json -k 2 -p secret/A/* 2>/dev/null | jq .

Is there anyway that I could read the secrets just based on key instead of providing the full path? like it works for rvault list

**Comment by kir4h** [comment]
I think the `include-paths` (`-i`) argument might suit your needs

```bash
# full contents
~  rvault list secret -v=0
/andalucia/almeria/ssh.key
/andalucia/malaga/passwd.conf
/barcelona/dev.null
/madrid/file1.txt
/madrid/leganes/file2.txt

# listing only secrets whose path match /andalucia*
~  rvault list secret -v=0 -i "/andalucia*"
/andalucia/almeria/ssh.key
/andalucia/malaga/passwd.conf

# reading those secrets 
~  rvault read secret -v=0 -i "/andalucia*" -f json | jq .
{
  "/andalucia/almeria/ssh.key": {
    "value": "This is \n another multiline \n file"
  },
  "/andalucia/malaga/passwd.conf": {
    "value": "This is \n a multiline \n file"
  }
}
# Another example filtering by secret name
# /andalucia contents 
~  rvault list secret -v=0 -p /andalucia
/andalucia/almeria/ssh.key
/andalucia/malaga/passwd.conf

# filtering to list only secrets like *ssh*
 ~  rvault list secret -v=0 -p /andalucia -i "*ssh*"
/andalucia/almeria/ssh.key

# filtering to read oly secrets like "*ssh*"
rvault read secret -f json -v=0 -p /andalucia -i "*ssh*" | jq .
{
  "/andalucia/almeria/ssh.key": {
    "value": "This is \n another multiline \n file"
  }
}
```
In your example it should be something like 

```bash
rvault read secret -f json -v=0 -p /A/B -i "gce*"
```
